### PR TITLE
Update images to mysql5.7

### PR DESCRIPTION
**Pull request by oatmealraisin**
Specifically, any mention of MySQL 5.6 is changed to 5.7, including doc
references.

@bparees ptal?

### CODE REVIEW

**Comment by bparees** [comment]
lgtm but blocked until the actual imagestream update PR goes in.

**Comment by luciddreamz** [comment]
Two things:

1. You forgot to update the other cakephp-mysql template: https://github.com/openshift/cakephp-ex/blob/master/openshift/templates/cakephp-mysql.json
2. Does this work as-is? I tried to use the existing template with MySQL 5.7 by just updating the version number, as you did here, and MySQL goes into a crash loop.

**Comment by oatmealraisin** [comment]
@luciddreamz Thanks for the catch, I thought I got everything. I've been able to reproduce your issue, I have not found a solution for it though.

**Comment by oatmealraisin** [comment]
@luciddreamz Hey! I've been testing this, and can't seem to reproduce the issue anymore. I cleared Docker of images, which is what I think fixed the issue.

**Comment by luciddreamz** [comment]
@oatmealraisin You should update PHP to PHP 7 while you're at it.

**Comment by bparees** [comment]
@luciddreamz we're going to do that separately since the PR to provide the php7 imagestream is still hung up.

**Comment by luciddreamz** [comment]
@bparees That's the same PR that includes both MySQL 5.7 and PHP 7?

**Comment by oatmealraisin** [comment]
@luciddreamz Sorry for not mentioning it, I've opened #12126 to get MySQL and Perl specifically.

**Comment by luciddreamz** [comment]
@oatmealraisin @bparees [#12126](https://github.com/openshift/origin/pull/12126) does not add the [MySQL 5.7 image stream](https://github.com/openshift/origin/pull/12005/files#diff-ed150e9a7412043c0565d61e1b484f1fR537). It only adds the template. Also, the image is either broken or the template needs to be updated. Added comment on that: https://github.com/openshift/origin/pull/12126#issuecomment-266066938

**Comment by luciddreamz** [comment]
@bparees On a related note, the recent set of updates moving credentials into secrets has broken all templates on OpenShift 3.3, as previously mentioned. What are we doing about that?

screen shot 2016-12-09 at 12 01 39 pm

**Comment by bparees** [comment]
> @oatmealraisin @bparees #12126 does not add the MySQL 5.7 image stream. It only adds the template. Also, the image is either broken or the template needs to be updated. Added comment on that: openshift/origin#12126 (comment)

@luciddreamz it does add the mysql5.7 imagstream: https://github.com/openshift/origin/pull/12126/files#diff-ed150e9a7412043c0565d61e1b484f1fR521

**Comment by oatmealraisin** [comment]
@bparees Is this clear to be merged now?

**Comment by bparees** [comment]
@oatmealraisin yup, thanks.

**Pull request merged**
