### PR TITLE
Adding composer.json, phpunit, and test cases

### LINKED ISSUE #24: Add test cases and post build hook
:diamond_shape_with_a_dot_inside: Adding a test case to the existing app didn't seen like the most fun and useful thing to do right now, so I'm opening this issue as a remainder to myself later or kind request for help if someone else wants to contribute sample unit tests.

This patch adds a build hook to run tests as part of the build flow in OpenShift:

``` diff
diff --git a/openshift/templates/cakephp-mysql.json b/openshift/templates/cakephp-mysql.json
index 52143da..c1140b0 100644
--- a/openshift/templates/cakephp-mysql.json
+++ b/openshift/templates/cakephp-mysql.json
@@ -106,7 +106,10 @@
               "secret": "${GITHUB_WEBHOOK_SECRET}"
             }
           }
-        ]
+        ],
+        "postCommit": {
+          "script": "./Console/cake test"
+        }
       }
     },
     {
diff --git a/openshift/templates/cakephp.json b/openshift/templates/cakephp.json
index b77dc0c..dae89ff 100644
--- a/openshift/templates/cakephp.json
+++ b/openshift/templates/cakephp.json
@@ -31,7 +31,7 @@
           }
         ],
         "selector": {
-          "name": "cakephp-example" 
+          "name": "cakephp-example"
         }
       }
     },
@@ -106,7 +106,10 @@
               "secret": "${GITHUB_WEBHOOK_SECRET}"
             }
           }
-        ]
+        ],
+        "postCommit": {
+          "script": "./Console/cake test"
+        }
       }
     },
     {
```

Note: `./Console/cake test` might need extra arguments. See http://book.cakephp.org/2.0/en/development/testing.html (since apparently we're using 2.x as of now).

It might be even just `cake test`, but we need `phpunit` installed. I tried to make at least the build hook working and leave actual tests for later, but I'm giving up trying to make it work for now :sweat_drops:

### PR DESCRIPTION
**Pull request by coreydaley**
Fixes #24

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees @luciddreamz @rhcarvalho ptal

**Comment by bparees** [comment]
lgtm, will let php guru @luciddreamz weigh in though.

**Comment by luciddreamz** [comment]
Hold off for a sec, there was a very specific reason I hadn't added composer here.

**Comment by coreydaley** [comment]
From what I can see, composer is supported by, and the preferred method of installing dependencies for, the s2i-php-container stuff: https://github.com/sclorg/s2i-php-container

**Comment by luciddreamz** [comment]
That is correct, and is not the issue here. I'll get back to you shortly.

**Comment by luciddreamz** [comment]
Looks good. Two super simple things:

1) Update the readme and mention composer.json. Maybe just copy this bit: https://github.com/sclorg/s2i-php-container/tree/master/7.0#source-repository-layout
2) Fill out the composer.json file to match the upstream, minus whatever you don't want in there, plus your changes: https://github.com/cakephp/cakephp/blob/2.9.5/composer.json

**Comment by coreydaley** [comment]
@luciddreamz updated per your suggestions

**Comment by luciddreamz** [comment]
Alright, looks good now.

**Comment by bparees** [comment]
the updated templates have been tested and the builds succeed when running the postcommit tests?

**Comment by coreydaley** [comment]
I was able to test two of them and they worked, but I am unable to get persistent storage setup on my local openshift to test that template.  I'll connect with you in a bit about it.

**Comment by bparees** [comment]
oc cluster up includes PVs out of the box now...

**Comment by coreydaley** [comment]
doh, thanks, i'll get that last template tested

**Comment by coreydaley** [comment]
Ok, all three templates run the tests during the build.

**Pull request merged**
