### PR TITLE
fix container image field

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

### CODE REVIEW

**Comment by bparees** [comment]
I think @jwforres showed me that these values show up in the webconsole when you're instantiating the template, so i think we want a cleaner value.  for jenkins i just went with this:
https://github.com/openshift/origin/blob/master/examples/jenkins/jenkins-ephemeral-template.json#L105

though i do like that your value conveys that it's a meaningless value and how it's actually getting set.

maybe APP_IMAGE_FROM_TRIGGER/MYSQL_IMAGE_FROM_TRIGGER ?  still feels wordy when it's going to show up on the console though.

**Comment by gabemontero** [comment]
How about TRIGGER_WILL_SET ?

**Comment by bparees** [comment]
SET_BY_TRIGGER?

help us @jwforres, you're our only hope.

**Comment by gabemontero** [comment]
I'm good with SET_BY_TRIGGER, but let's head to Tatooine and see what @jwforres says

**Comment by bparees** [comment]
let's go with SET_BY_TRIGGER, it sounds like @jwforres is going to make some changes to the console so this value won't be shown if an ICT is defined.

**Comment by bparees** [comment]
so i merged this prematurely, apparently we want to use an empty string as the value.
@gabemontero can you confirm that:
1) the DC doesn't blow up with an emptystring image field value?
2) the web console doesn't blow up when you try to instantiate that template?  (it's going to show something like "image: " i guess, for now)

**Comment by gabemontero** [comment]
It does blow up, failing k8s validation:
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/validation.go#L1311-L1313

**Pull request merged**
