### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by jhadvig**
CakePHP basic demo application. We still need to settle down on the structure of the README and the demo app so all the *-ex apps will have the same structure + similar README

### CODE REVIEW

**Comment by jhadvig** [comment]
@rhcarvalho @bparees @ewolinetz PTAL

**Comment by mfojtik** [comment]
@jhadvig can you just split this into 2 commits, 1 commit with common PHP files and second with your changes.

**Comment by jhadvig** [comment]
@mfojtik is it really neccessary ? Like there were a lot of changes, but I can do it if its really necessary.
We (I @rhcarvalho) tested the templates and (db and non-db) and both were working without problem.

**Comment by jhadvig** [comment]
@mfojtik I've splinted the PR into two commits. Please check the `Necessary changes` commit.
@rhcarvalho @bparees PTAL

**Comment by rhcarvalho** [comment]
@jhadvig what version of CakePHP is that? I'm afraid we might be carrying over some unnecessary modifications to a vanilla CakePHP project that were required in OSv2?

**Comment by kargakis** [comment]
:sunny: :tropical_drink:

**Comment by jhadvig** [comment]
@rhcarvalho the version is 2.4.2

**Comment by jhadvig** [comment]
@mfojtik @bparees @rhcarvalho I've updated the whole PR due to your comments + welcome page + readme. Also tested the DB and non-DB example and everything was working. PTAL
:ship:it

**Comment by rhcarvalho** [comment]
Our comments on previous commits disappeared :cry:

**Comment by rhcarvalho** [comment]
https://github.com/jhadvig/cakephp-ex/commit/e1f6929b0f55073741c37bde2b0e180bffcff6fa#diff-4a88f225d02c576f44996e600ad1646bR3

maybe use `source` to run the default assemble script, so that it is executed in the same shell, keeping env vars, etc

**Comment by bparees** [comment]
taking @jhadvig 's word on this working, we can iterate on @rhcarvalho 's changes and other stuff, but want to get this landed for the omment.

**Comment by jhadvig** [comment]
@kargakis :sweat_smile:

**Pull request merged**
