### PR TITLE
Add liveness and readiness probe

### PR DESCRIPTION
**Pull request by mfojtik**
@bparees FYI

(I failed to add minimal health.php because cakephp is crazy and it will require special layout/view/etc...)

### CODE REVIEW

**Comment by bparees** [comment]
so this one will pass readiness even if the db isn't up?

**Comment by mfojtik** [comment]
@bparees no, cakephp will return error in that case... the problem is that liveness check will keep increasing the page counter ;-) but I can live with that....

**Comment by bparees** [comment]
really?  I thought the cakephp app was smart enough to just report "no db configured" in the index page if the DB wasn't available, i'm surprised it returns an error.

**Comment by mfojtik** [comment]
oh you are right, we have if there.... ok i will have to figure out how to
test db connection..
maybe add url paramerer that disable the if.

**Comment by mfojtik** [comment]
@bparees OK now we are checking the connection to the database. Also we will have to talk about the pre-deployment "abort" policy for migrations... I changed that to "retry", but there is a catch :-)

**Pull request merged**
